global:
  scrape_interval: 15s  # How often to scrape targets by default
  evaluation_interval: 15s

scrape_configs:
  - job_name: "userservice"
    scrape_interval: 5s
    metrics_path: "/metrics"
    scheme: "http"
    static_configs:
      - targets:
        - "userservice:80"

  - job_name: "postservice"
    scrape_interval: 5s
    metrics_path: "/metrics"
    scheme: "http"
    static_configs:
      - targets:
        - "postservice:80"

  - job_name: "frontendservice"
    scrape_interval: 5s
    metrics_path: "/metrics"
    scheme: "http"
    static_configs:
      - targets:
        - "frontendservice:80"
