version: '3.8'

services:
  frontendservice:
    image: frontendservice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7080:80"
      - "7443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./logs:/app/logs
