version: '3.8'

services:
  userservice:
    image: userservice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5080:80"
      - "5443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./logs:/app/logs
